---
title: "Character visualisations"
author: ""
---

<!--

This document can be compiled into a PDF, HTML or MS Word document by clicking
the "knit" button that appears when the file is opened in RStudio
(https://posit.co/downloads/)

Modify the file for your purposes by editing the code block below.

-->

```{r initialization, echo = FALSE}
source("common.R") # Leave this line here: it loads necessary functions

# 
matrixFile <- LatestMatrix() # To use a specific file, write its path here
# For example: 
# matrixFile <- "C:\path\to\file.nex"

dataset <- ReadAsPhyDat(matrixFile) # Use instead ReadTntAsPhyDat() for .tnt files

# Load a tree on which to map characters
tree <- LatestTree(dataset)
# To load a specific tree, see instructions at 
# https://ms609.github.io/TreeTools/articles/load-trees.html
```

# Character reconstructions {#reconstructions}

This report defines each character in the matrix, justifying the score of 
particular taxa where relevant.
Each character has been mapped onto a tree, with each tip labelled according to
its coding in the matrix.
These states have been used to reconstruct the condition of each internal node,
using the parsimony method of @Brazeau2018 as implemented in the _R_ package
"TreeSearch".

As different trees may give different reconstructions, the character mappings 
do not definitively establish how any given character evolved; rather, they
serve to display how each character has been coded, and thus how it fits
onto a given tree.  `r if(knitr::is_html_output()) '<a href="javascript:toggleSVG();">Click here</a> to <span id="showOrHide">hide</span> the character reconstructions below.'`

```{R load-the-characters, echo=FALSE, message=FALSE}
# Uniform edge length in plot
tree$edge.length <- rep(1, nrow(tree$edge))
my_chars <- ReadCharacters(matrixFile)
char_names <- gsub("^'(.+)'$", "\\1", colnames(my_chars))
n_char <- ncol(my_chars)
char_parts <- strsplit(char_names, ": ")
char_nesting <- vapply(char_parts, length, 0L)

taxa_names <- unique(rownames(my_chars))
taxa_plaintext <- gsub("_", " ", taxa_names, fixed = TRUE)
taxa_italic <- paste0("_", taxa_plaintext, "_")

index <- attr(my_data, "index")
```

```{R character-mapping, echo=FALSE, fig.height=6.2, fig.width=7.1, results="asis"}
prev_char_parts <- "NONE"

subheadings <- c("Digestive tract: Anus: Presence",
                 "Gametes: Spermatozoa: Nucleus: Shape",
                 "Gametes: Egg: Size",
                 paste("Sclerites:",
                       c("Bivalved", "Dorsal valve: Growth direction",
                         "Ventral valve: Growth direction",
                         "Ornament: Concentric ornament",
                         "Composition: Mineralogy",
                         "Structure: Stratiform lamellae expressed at surface")),
                 paste("Larva:", c("Cilia: Metatroch", 
                    "Apical organ: Muscles extending to the hyposphere")))

#for (i in 14:17) {
for (i in seq_len(n_char)) {
  
  # Print character heading:
  this_char_parts <- char_parts[[i]]
  next_char_parts <- if (i == n_char) "LAST_CHARACTER" else char_parts[[i + 1L]]
  PrintCharacterHeading(char_names[i], i, prev_char_parts, this_char_parts, 
                        next_char_parts, subheadings)
  prev_char_parts <- this_char_parts
  
  # Plot character reconstruction:
  PlotCharacterMapping(char = my_chars[, i], stateLabels = my_states[[i]],
                       singleTree = uniqueTrees[[1]], legendText = ci_text[i, 1],
                       canvas = svgCanvas, treeNames = treeNames,
                       analysisLabels = analysisLabels, charIndex = i,
                       svgFilename = paste0('_book/', sprintf(fileNamer, '%s', i)),
                       SetPar = par(mar=rep(0.2, 4), cex=0.7))
  
  # Plot character details:
  cat(paste0("  \n\n > **Character ", i, ": ", Italicize(char_names[i]), "**  \n>\n"))
  if (!is.null(getOption('localInstance')) || knitr::is_html_output()) {
    lineHeight <- 24L
    
    states_matrix <- apply.reconstruction(uniqueTrees[[1]], my_chars[, i])
    matrix_data <- MatrixData(states_matrix, states_matrix, state.labels=my_states[[i]])
    legend_labels <- matrix_data$legend
    legend_col    <- matrix_data$legend_col
    legendY <- round(lineHeight * seq_along(legend_labels), 1)
    cat(paste0('>  <svg xmlns="http://www.w3.org/2000/svg" version="1.1',
              '" viewBox="0 0 ', getOption('svgWidth'), ' ', 
              lineHeight * length(legend_labels) + lineHeight - 5L,
               # For T/N statement
               '" class="statesLegend">',
        paste0('<path d="M0,', legendY - 15L, 'h22" stroke="', legend_col,
               ifelse(legend_col == 'lightgrey', '" class="inapplicable', ''),
               '"></path>', collapse=''),
        '<text x="30" y="-10" class="legendLabels">', 
        paste0('<tspan x="30" dy="', lineHeight, '">', legend_labels, '</tspan>', collapse=''),
        '<tspan x=0 dy="', lineHeight, '">', 
        ifelse (IsTransformational(my_states[[i]]), "Transformational", "Neomorphic"),
        ' character.</tspan>',
        '</text></svg> \n>\n'))
  } else {
    PrintStates(Italicize(my_states[[i]]))
  }
  cat("  \n\n")
  char_notes_i <- char_notes[[i]]
  state_notes_i <- char_notes_i[[2]]
  state_notes_i <- state_notes_i[!names(state_notes_i) %in% ignored_taxa]
  if (length(char_notes_i[[1]]) > 0) cat(Italicize(char_notes_i[[1]]), "  \n")
  if (length(state_notes_i) > 0) {
    PrintStateNotes(state_notes_i, taxa_names, taxa_italic, i, Italicize)
  }
  if (my_states[[i]][[1]] != "''") PrintNaughtyInapplicables(my_chars[, i])
  cat("  \n") # Clear line, ready for next block
}
PrintSwitcher(length(uniqueTrees))
```
