piwe=;
mxram 4096;

proc ENTER_INPUT_FILENAME_HERE;
outgroup ENTER_OUTGROUP_LABEL_HERE;

/* If this file is in the same directory as your data file, */
/* simply type tnt into the TNT command line to run this script. */

macro=;
xmult:rat25 drift25 hits 15 level 4 chklevel 5;
/* 15 hits gives a quick but less comprehensive run */

var: nt;

piwe-    ;xmult;tsav *ew.tre;sav;tsav/;nelsen *;set nt ntrees;ttag=;resample=sym replications 100 frequency from 'nt';log ew.sym;ttag/;log/; keep 0; ttag-; hold 10000;
/* nelsen /L for consensus w/o taxon L */
xpiwe=;
piwe=10;xmult;tsav *xpiwe10.tre;sav;tsav/;nelsen *;set nt ntrees;ttag=;resample=frequency from 'nt';log xpiwe10.sym;ttag/;log/; keep 0; ttag-; hold 10000;
piwe=40 ;xmult;tsav *xpiwe40.tre;sav; tsav/;nelsen *;set nt ntrees;ttag=;resample=frequency from 'nt';log xpiwe40.sym; ttag/;log/; keep 0; ttag-; hold 10000;
piwe=3   ;xmult;tsav *xpiwe3.tre;sav;   tsav/;nelsen *;set nt ntrees;ttag=;resample=frequency from 'nt';log xpiwe3.sym;   ttag/;log/; keep 0; ttag-; hold 10000;
piwe=20  ;xmult;tsav *xpiwe20.tre;sav;  tsav/;nelsen *;set nt ntrees;ttag=;resample=frequency from 'nt';log xpiwe20.sym;  ttag/;log/; keep 0; ttag-; hold 10000;
piwe=6  ;xmult;tsav *xpiwe6.tre;sav;  tsav/;nelsen *;set nt ntrees;ttag=;resample=frequency from 'nt';log xpiwe6.sym;  ttag/;log/; keep 0; ttag-; hold 10000;

/* 1000 hits gives a slow but incredibly comprehensive set of results */
xmult:hits 1000;

piwe-    ;xmult;tsav *ew.tre;sav;tsav/;nelsen *;set nt ntrees;ttag=;resample=sym replications 5000 frequency from 'nt';log ew.sym;ttag/;ttag/;log/; keep 0; ttag-; hold 10000;
xpiwe=;
piwe=10;xmult;tsav *xpiwe10.tre;sav;tsav/;nelsen *;set nt ntrees;ttag=;resample=frequency from 'nt';log xpiwe10.sym;ttag/;log/; keep 0; ttag-; hold 10000;
piwe=40 ;xmult;tsav *xpiwe40.tre;sav; tsav/;nelsen *;set nt ntrees;ttag=;resample=frequency from 'nt';log xpiwe40.sym; ttag/;log/; keep 0; ttag-; hold 10000;
piwe=3   ;xmult;tsav *xpiwe3.tre;sav;   tsav/;nelsen *;set nt ntrees;ttag=;resample=frequency from 'nt';log xpiwe3.sym;   ttag/;log/; keep 0; ttag-; hold 10000;
piwe=20  ;xmult;tsav *xpiwe20.tre;sav;  tsav/;nelsen *;set nt ntrees;ttag=;resample=frequency from 'nt';log xpiwe20.sym;  ttag/;log/; keep 0; ttag-; hold 10000;
piwe=6  ;xmult;tsav *xpiwe6.tre;sav;  tsav/;nelsen *;set nt ntrees;ttag=;resample=frequency from 'nt';log xpiwe6.sym;  ttag/;log/; keep 0; ttag-; hold 10000;

macro -;
